<?php

declare(strict_types=1);

/**
 * Certify which OpenSearch versions accept the queries this library claims to
 * render, and write the answer to resources/versions.json.
 *
 * Maintainer tool. It is not shipped in the Composer package and the offline
 * test suite never runs it — that one reads committed files and must stay
 * network-free. This one needs real clusters:
 *
 *     make certify
 *     make certify OS2_VERSION=2.11.1 OS3_VERSION=3.0.0
 *
 * What it proves, and what it does not: sending every probe to a live node
 * shows that the version *has* the query type and parses the body. It says
 * nothing about whether our rendering of that query is faithful — that is what
 * the unit suite is for. The two together are the guarantee; neither is alone.
 *
 * A probe that fails for any reason other than "unknown query" is treated as a
 * broken probe, not as a version difference, and stops the run. Recording our
 * own malformed DSL as "this version does not support X" would poison the very
 * file this tool exists to produce.
 */
const PROBES = __DIR__ . '/../resources/probes.json';
const COVERAGE = __DIR__ . '/../resources/coverage.json';
const OUTPUT = __DIR__ . '/../resources/versions.json';

/** The index the probes run against. Dropped and recreated on every run. */
const INDEX = 'os-query-digest-certify';

$configured = getenv('OPENSEARCH_URLS');
$configured = is_string($configured) && $configured !== ''
    ? $configured
    : 'http://localhost:9202,http://localhost:9203';

$urls = [];
foreach (explode(',', $configured) as $candidate) {
    $candidate = trim($candidate);
    if ($candidate !== '') {
        $urls[] = $candidate;
    }
}

if ($urls === []) {
    fwrite(STDERR, "No cluster to talk to. Set OPENSEARCH_URLS.\n");
    exit(1);
}

$probes = readJson(PROBES);
$coverage = readJson(COVERAGE);

$queries = arr($probes, 'queries');
$unprobed = arr($probes, 'unprobed');
$index = arr($probes, 'index');

$clusters = [];
$results = [];

foreach ($urls as $url) {
    $root = request($url, 'GET', '/');
    if ($root['status'] !== 200) {
        fwrite(STDERR, "No cluster answering at {$url} — is `make certify` starting it?\n");
        exit(1);
    }

    $version = str(dig($root['body'], ['version', 'number']));
    $distribution = str(dig($root['body'], ['version', 'distribution']));
    fwrite(STDOUT, "== {$distribution} {$version} ({$url})\n");

    prepareIndex($url, $index);

    $accepted = 0;
    $missing = [];

    foreach ($queries as $type => $query) {
        $outcome = probe($url, $query);

        if ($outcome === true) {
            $results[$type][$version] = 'accepted';
            ++$accepted;
            continue;
        }

        if (isUnknownQuery($outcome)) {
            $results[$type][$version] = 'unsupported';
            $missing[] = $type;
            continue;
        }

        // Anything else is our fault: a probe body this version rejects for a
        // reason that has nothing to do with the query type existing.
        fwrite(STDERR, "\nBroken probe for [{$type}] against {$version}:\n  {$outcome}\n");
        fwrite(STDERR, "Fix resources/probes.json — a bad probe must never be recorded as a version difference.\n");
        exit(1);
    }

    // Deliberately no endpoint: a committed artefact recording
    // `http://localhost:9202` tells a reader nothing and churns the diff.
    $clusters[] = [
        'distribution' => $distribution,
        'version' => $version,
    ];

    fwrite(STDOUT, sprintf(
        "   %d accepted, %d unsupported%s\n",
        $accepted,
        count($missing),
        $missing === [] ? '' : ': ' . implode(', ', $missing),
    ));
}

ksort($results);

$matrix = [
    '_comment' => 'Generated by tools/certify.php — do not edit by hand. Each query type carries the verdict of a live cluster, per version.',
    'generated_at' => gmdate('Y-m-d\TH:i:s\Z'),
    'clusters' => $clusters,
    'results' => $results,
    'unprobed' => $unprobed,
];

file_put_contents(
    OUTPUT,
    json_encode($matrix, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n",
);

fwrite(STDOUT, sprintf(
    "\nwrote %s: %d types across %d clusters\n",
    basename(OUTPUT),
    count($results),
    count($clusters),
));

$orphans = array_diff(array_keys(arr($coverage, 'query')), array_keys($results), array_keys($unprobed));

if ($orphans !== []) {
    fwrite(STDERR, 'Not probed and not explained: ' . implode(', ', $orphans) . "\n");
    fwrite(STDERR, "Add a probe to resources/probes.json, or say why it cannot have one under \"unprobed\".\n");
    exit(1);
}

fwrite(STDOUT, "now run the tests — CertificationTest guards the file.\n");

/**
 * Drop and recreate the probe index, so a mapping change in probes.json takes
 * effect without anyone having to remember to clean up.
 *
 * @param array<mixed> $definition
 */
function prepareIndex(string $url, array $definition): void
{
    request($url, 'DELETE', '/' . INDEX);

    $created = request($url, 'PUT', '/' . INDEX, $definition);
    if ($created['status'] !== 200) {
        fwrite(STDERR, 'Could not create ' . INDEX . " on {$url}:\n  " . json_encode($created['body']) . "\n");
        exit(1);
    }
}

/**
 * @param mixed $query
 *
 * @return true|string true when the cluster accepted the query, the failure
 *                     reason otherwise
 */
function probe(string $url, $query)
{
    $response = request($url, 'POST', '/' . INDEX . '/_search', ['query' => $query, 'size' => 0]);

    if ($response['status'] === 200) {
        return true;
    }

    $reason = str(dig($response['body'], ['error', 'root_cause', 0, 'reason']));
    if ($reason === '') {
        $reason = str(dig($response['body'], ['error', 'reason']));
    }

    return $reason !== ''
        ? $reason
        : 'HTTP ' . $response['status'] . ' ' . json_encode($response['body']);
}

/**
 * The one failure that means "this version does not have that query type"
 * rather than "the probe is wrong".
 */
function isUnknownQuery(string $reason): bool
{
    return strpos($reason, 'unknown query') !== false
        || strpos($reason, 'no [query] registered for') !== false;
}

/**
 * @param non-empty-string  $method
 * @param array<mixed>|null $body
 *
 * @return array{status:int,body:array<mixed>|null}
 */
function request(string $url, string $method, string $path, ?array $body = null): array
{
    $handle = curl_init($url . $path);
    if ($handle === false) {
        fwrite(STDERR, "Could not open a connection to {$url}\n");
        exit(1);
    }

    curl_setopt($handle, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($handle, CURLOPT_CUSTOMREQUEST, $method);
    curl_setopt($handle, CURLOPT_TIMEOUT, 30);
    curl_setopt($handle, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);

    if ($body !== null) {
        curl_setopt($handle, CURLOPT_POSTFIELDS, encode($body));
    }

    $raw = curl_exec($handle);
    $status = curl_getinfo($handle, CURLINFO_HTTP_CODE);
    $decoded = is_string($raw) ? json_decode($raw, true) : null;

    return [
        'status' => $status,
        'body' => is_array($decoded) ? $decoded : null,
    ];
}

/**
 * json_encode, with empty arrays restored to empty objects.
 *
 * `{"match_all": {}}` decoded into arrays is `['match_all' => []]`, and
 * re-encoding that yields `{"match_all": []}` — which OpenSearch answers with
 * "query malformed, no start_object after query name" instead of running it.
 * Decoding into objects would keep the distinction, at the price of turning
 * every field access in this file into `mixed`; fixing it in the one place it
 * matters is cheaper.
 *
 * The trade is that a genuinely empty *list* would also come out as `{}`. No
 * probe needs one today — if one ever does, this is the function to look at.
 *
 * @param array<mixed> $body
 *
 * @return non-empty-string
 */
function encode(array $body): string
{
    $json = json_encode(objectifyEmpty($body));

    if (!is_string($json)) {
        fwrite(STDERR, "A probe body could not be encoded — check resources/probes.json.\n");
        exit(1);
    }

    return $json;
}

/**
 * @param mixed $value
 *
 * @return mixed
 */
function objectifyEmpty($value)
{
    if (!is_array($value)) {
        return $value;
    }

    if ($value === []) {
        return new stdClass();
    }

    $out = [];
    foreach ($value as $key => $item) {
        $out[$key] = objectifyEmpty($item);
    }

    return $out;
}

/**
 * @param mixed                 $node
 * @param array<int,string|int> $path
 *
 * @return mixed
 */
function dig($node, array $path)
{
    foreach ($path as $step) {
        if (!is_array($node) || !array_key_exists($step, $node)) {
            return null;
        }
        $node = $node[$step];
    }

    return $node;
}

/**
 * @param array<mixed> $value
 *
 * @return array<string,mixed>
 */
function arr(array $value, string $key): array
{
    $found = $value[$key] ?? null;

    if (!is_array($found)) {
        return [];
    }

    $out = [];
    foreach ($found as $name => $item) {
        $out[(string) $name] = $item;
    }

    return $out;
}

/**
 * @param mixed $value
 */
function str($value): string
{
    return is_string($value) ? $value : '';
}

/**
 * @return array<mixed>
 */
function readJson(string $file): array
{
    $contents = file_get_contents($file);
    $decoded = is_string($contents) ? json_decode($contents, true) : null;

    if (!is_array($decoded)) {
        fwrite(STDERR, "Unreadable: {$file}\n");
        exit(1);
    }

    return $decoded;
}
