<?php

declare(strict_types=1);

/**
 * Refresh resources/opensearch-spec.json from the official OpenSearch API
 * specification.
 *
 * Maintainer tool. It is not shipped in the Composer package and the test suite
 * never runs it: tests read the committed snapshot, offline and deterministic.
 * Run it when you want to check whether OpenSearch has grown new query or
 * aggregation types:
 *
 *     make spec
 *     make spec SPEC_REF=e027edc     # pin a commit for a reproducible snapshot
 *
 * Then run the tests — SpecCoverageTest fails on any type the snapshot gained
 * or lost, forcing a conscious decision instead of silent drift.
 *
 * symfony/yaml is a require-dev dependency: the spec is published as YAML and
 * PHP has no core YAML parser. Consumers of the library never install it.
 */

use Symfony\Component\Yaml\Yaml;

$autoload = __DIR__ . '/../vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(STDERR, "Run `composer install` first.\n");
    exit(1);
}
require $autoload;

const REPO = 'opensearch-project/opensearch-api-specification';
const FILES = [
    'spec/schemas/_common.query_dsl.yaml',
    'spec/schemas/_common.aggregations.yaml',
];
/** `aggs` / `aggregations` are the sub-aggregation slots, not aggregation types. */
const AGG_SLOTS = ['aggs', 'aggregations'];

$ref = getenv('SPEC_REF');
$ref = is_string($ref) && $ref !== '' ? $ref : 'main';

$raw = [];
foreach (FILES as $path) {
    fwrite(STDOUT, "fetching {$path} @ {$ref}\n");
    $raw[$path] = fetch("https://raw.githubusercontent.com/" . REPO . "/{$ref}/{$path}");
}

$querySpec = Yaml::parse($raw[FILES[0]]);
$queryTypes = array_keys($querySpec['components']['schemas']['QueryContainer']['properties']);
sort($queryTypes, SORT_STRING);

$aggSpec = Yaml::parse($raw[FILES[1]]);
$schemas = $aggSpec['components']['schemas'];
$members = $schemas['AggregationContainer']['allOf'][1]['oneOf'];

$aggTypes = [];
foreach ($members as $member) {
    foreach (namesFrom($schemas, $member) as $name) {
        $aggTypes[$name] = true;
    }
}
$aggTypes = array_values(array_diff(array_keys($aggTypes), AGG_SLOTS));
sort($aggTypes, SORT_STRING);

[$sha, $date] = headCommit($ref);

$snapshot = [
    '_comment' => 'Generated by tools/refresh-spec.php — do not edit by hand.',
    'source' => [
        'repository' => 'https://github.com/' . REPO,
        'ref' => $ref,
        'commit' => $sha,
        'commit_date' => $date,
        'fetched_at' => gmdate('Y-m-d\TH:i:s\Z'),
        'files' => FILES,
    ],
    'opensearch_version_floor' => maxVersion($raw),
    'query_types' => $queryTypes,
    'aggregation_types' => $aggTypes,
];

$output = __DIR__ . '/../resources/opensearch-spec.json';
file_put_contents(
    $output,
    json_encode($snapshot, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n"
);

fwrite(STDOUT, sprintf(
    "wrote %d query types and %d aggregation types\n",
    count($queryTypes),
    count($aggTypes)
));
fwrite(STDOUT, "now run the tests — SpecCoverageTest will flag anything new.\n");

/**
 * Collect the property names one oneOf member contributes, following $ref.
 *
 * @param array<string,mixed> $schemas
 * @param array<string,mixed> $node
 *
 * @return array<int,string>
 */
function namesFrom(array $schemas, array $node, int $depth = 0): array
{
    $names = [];

    if (isset($node['$ref']) && $depth < 3) {
        $target = $schemas[basename((string) $node['$ref'])] ?? [];
        $members = isset($target['allOf']) && is_array($target['allOf']) ? $target['allOf'] : [$target];
        foreach ($members as $member) {
            if (is_array($member)) {
                $names = array_merge($names, namesFrom($schemas, $member, $depth + 1));
            }
        }
    }

    if (isset($node['properties']) && is_array($node['properties'])) {
        $names = array_merge($names, array_map('strval', array_keys($node['properties'])));
    }

    return $names;
}

/**
 * Highest OpenSearch version named by an x-version-added/deprecated marker.
 *
 * The spec does not tag every type, so this is a floor, not a guarantee: it
 * says the snapshot knows about features up to that release.
 *
 * @param array<string,string> $documents
 */
function maxVersion(array $documents): ?string
{
    $found = [];
    foreach ($documents as $text) {
        if (preg_match_all("/x-version-(?:added|deprecated):\s*'?([0-9.]+)'?/", $text, $matches) > 0) {
            foreach ($matches[1] as $version) {
                $found[$version] = true;
            }
        }
    }

    if ($found === []) {
        return null;
    }

    $versions = array_keys($found);
    usort($versions, static function (string $a, string $b): int {
        return version_compare($a, $b);
    });

    return (string) end($versions);
}

/**
 * @return array{0:string|null,1:string|null}
 */
function headCommit(string $ref): array
{
    try {
        $payload = json_decode(fetch('https://api.github.com/repos/' . REPO . '/commits/' . $ref), true);
        if (!is_array($payload) || !isset($payload['sha'])) {
            throw new RuntimeException('unexpected payload');
        }

        return [(string) $payload['sha'], (string) ($payload['commit']['committer']['date'] ?? '')];
    } catch (Throwable $error) {
        // Rate limiting or offline: the snapshot is still valid, just less traceable.
        fwrite(STDERR, '  ! could not read commit metadata: ' . $error->getMessage() . "\n");

        return [null, null];
    }
}

function fetch(string $url): string
{
    $userAgent = 'os-query-digest-spec-refresh';

    if (function_exists('curl_init')) {
        $handle = curl_init($url);
        if ($handle === false) {
            throw new RuntimeException('could not initialise curl');
        }
        curl_setopt($handle, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($handle, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($handle, CURLOPT_USERAGENT, $userAgent);
        curl_setopt($handle, CURLOPT_HTTPHEADER, ['Accept: application/vnd.github+json']);
        $body = curl_exec($handle);
        $status = (int) curl_getinfo($handle, CURLINFO_RESPONSE_CODE);
        $error = curl_error($handle);
        curl_close($handle);

        if (!is_string($body) || $status >= 400) {
            throw new RuntimeException(sprintf('GET %s failed (HTTP %d) %s', $url, $status, $error));
        }

        return $body;
    }

    $context = stream_context_create(['http' => [
        'header' => "User-Agent: {$userAgent}\r\nAccept: application/vnd.github+json\r\n",
    ]]);
    $body = @file_get_contents($url, false, $context);
    if (!is_string($body)) {
        throw new RuntimeException('GET ' . $url . ' failed (enable ext-curl or allow_url_fopen)');
    }

    return $body;
}
